### ISSUE TITLE
GÖREV İŞİNİ SONSUZ DÖNGÜYE ALMAMA İŞİ

### ISSUE THREAD

**Issue by VoltrY** [atiAI/ati#8]
örneğin ikinci dereceden denklemlerle alakalı kullanıcıya bir görev verildi. Kullanıcı bu konuyla alakalı chatbota tekrar mesaj attığında bu konuyla alakalı görev vermeden onunla konuşması. ( ya da  kartlar bölümüne karta tıklandığında bu konuyla alakalı chat bota soru sor kısmı eklenip ayrı bi yapay zekayla sadece yardım amaçlı kullanılabilir. hangisi daha kolay olursa o yapılır.)

**Comment by creeperkafasi** [comment]
7290c5b4469f495edea04f7803513ea1eedb09be tamam
